FROM python:3.10

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir --default-timeout=100 -r requirements.txt

RUN pip install --no-cache-dir --default-timeout=100 \
    -i https://pypi.org/simple \
    -r requirements.txt

CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000"]