spring:

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: backend

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}

ai:
  service:
    url: ${AI_SERVICE_URL}

logging:
  level:
    org.springframework.web: DEBUG
    root: INFO
    com.app: DEBUG
